language: node_js

script:
  # Pipe javascript test coverage lcov.info results into coveralls
  # Yarn passes the --coverage argument and any others into the react-scripts-ts test script
  - yarn test --coverage && cat ./coverage/lcov.info && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

  # TODO: Consider building and deploying after this point in an after_script or deploy section?
  # See: http://kamranicus.com/blog/2015/02/26/continuous-deployment-with-travis-ci/

cache:
  yarn: true
